/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *    
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2014 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov, Rien Quirynen, KU Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC)
 *    under supervision of Moritz Diehl. All rights reserved.
 *    
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *    
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *    
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *    
 */


#include "acado_common.h"


void acado_rhs(const real_t* in, real_t* out)
{
const real_t* xd = in;
const real_t* u = in + 6;
/* Vector of auxiliary variables; number of elements: 2. */
real_t* a = acadoWorkspace.rhs_aux;

/* Compute intermediate quantities: */
a[0] = ((xd[1])*(xd[1]));
a[1] = ((((real_t)(4.7999999999999998e-01)*((real_t)(1.0000000000000000e+00)-(xd[2]/(real_t)(5.0000000000000000e+01))))*xd[1])/(((real_t)(1.2000000000000000e+00)+xd[1])+(a[0]/(real_t)(2.2000000000000000e+01))));

/* Compute outputs: */
out[0] = (((real_t)(-1.4999999999999999e-01)*xd[0])+(a[1]*xd[0]));
out[1] = (((real_t)(1.4999999999999999e-01)*(u[0]-xd[1]))-((a[1]/(real_t)(4.0000000000000002e-01))*xd[0]));
out[2] = (((real_t)(-1.4999999999999999e-01)*xd[2])+((((real_t)(2.2000000000000002e+00)*a[1])+(real_t)(2.0000000000000001e-01))*xd[0]));
out[3] = xd[0];
out[4] = u[0];
out[5] = (((real_t)(1.4999999999999999e-01)*xd[2])/(real_t)(4.8000000000000000e+01));
}

/* Fixed step size:0.24 */
int acado_integrate( real_t* const rk_eta, int resetIntegrator )
{
int error;

int run1;
acadoWorkspace.rk_ttt = 0.0000000000000000e+00;
acadoWorkspace.rk_xxx[6] = rk_eta[6];

for (run1 = 0; run1 < 10; ++run1)
{
acadoWorkspace.rk_xxx[0] = + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + rk_eta[5];
acado_rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_kkk );
acadoWorkspace.rk_xxx[0] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[0] + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[1] + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[2] + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[3] + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[4] + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[5] + rk_eta[5];
acado_rhs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_kkk[ 6 ]) );
acadoWorkspace.rk_xxx[0] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[6] + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[7] + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[8] + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[9] + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[10] + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + (real_t)1.2000000000000000e-01*acadoWorkspace.rk_kkk[11] + rk_eta[5];
acado_rhs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_kkk[ 12 ]) );
acadoWorkspace.rk_xxx[0] = + (real_t)2.3999999999999999e-01*acadoWorkspace.rk_kkk[12] + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + (real_t)2.3999999999999999e-01*acadoWorkspace.rk_kkk[13] + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + (real_t)2.3999999999999999e-01*acadoWorkspace.rk_kkk[14] + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + (real_t)2.3999999999999999e-01*acadoWorkspace.rk_kkk[15] + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + (real_t)2.3999999999999999e-01*acadoWorkspace.rk_kkk[16] + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + (real_t)2.3999999999999999e-01*acadoWorkspace.rk_kkk[17] + rk_eta[5];
acado_rhs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_kkk[ 18 ]) );
rk_eta[0] += + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[0] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[6] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[12] + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[18];
rk_eta[1] += + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[1] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[7] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[13] + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[19];
rk_eta[2] += + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[2] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[8] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[14] + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[20];
rk_eta[3] += + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[3] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[9] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[15] + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[21];
rk_eta[4] += + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[4] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[10] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[16] + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[22];
rk_eta[5] += + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[5] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[11] + (real_t)7.9999999999999988e-02*acadoWorkspace.rk_kkk[17] + (real_t)3.9999999999999994e-02*acadoWorkspace.rk_kkk[23];
acadoWorkspace.rk_ttt += 1.0000000000000001e-01;
}
error = 0;
return error;
}

