/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *    
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov, Rien Quirynen, KU Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC)
 *    under supervision of Moritz Diehl. All rights reserved.
 *    
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *    
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *    
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *    
 */


#include "acado.h"


#include "mex.h"

/* GLOBAL VARIABLES FOR THE ACADO REAL-TIME ALGORITHM: */
/* --------------------------------------------------- */
   ACADOvariables acadoVariables;
   ACADOworkspace acadoWorkspace;

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

    int i;
    int Nx, Nt, Nu, Np;
    real_t *f, *x, *u, *p;
    real_t y[ACADO_NX+ACADO_NXA+ACADO_NU+ACADO_NP+ACADO_NDX];
    
    if (nrhs != 2+(ACADO_NU>0)+(ACADO_NP>0)) {
        mexErrMsgTxt( "Check the number of input arguments !!" );
    }
    if (nlhs > 1) {
        mexErrMsgTxt( "Check the number of output arguments !!" );
    }
    
    Nt = mxGetM(prhs[0])*mxGetN(prhs[0]);
    Nx = mxGetM(prhs[1])*mxGetN(prhs[1]);
    #if ACADO_NU > 0
        Nu = mxGetM(prhs[2])*mxGetN(prhs[2]);
    #else
        Nu = 0;
    #endif
    #if ACADO_NP > 0
        Np = mxGetM(prhs[3])*mxGetN(prhs[3]);
    #else
        Np = 0;
    #endif
    
    if (Nt != 1) {
        mexErrMsgTxt( "Check the dimension of the first input argument !!" );
    }
    if (Nx != ACADO_NX+ACADO_NXA+ACADO_NDX) {
        mexErrMsgTxt( "Check the dimension of the second input argument !!" );
    }
    if (Nu != ACADO_NU) {
        mexErrMsgTxt( "Check the dimension of the control input argument !!" );
    }
    if (Np != ACADO_NP) {
        mexErrMsgTxt( "Check the dimension of the parameter input argument !!" );
    }
    
    x = mxGetPr(prhs[1]);
    #if ACADO_NU > 0
        u = mxGetPr(prhs[2]);
    #endif
    #if ACADO_NP > 0
        p = mxGetPr(prhs[3]);
    #endif
    for( i = 0; i < ACADO_NX+ACADO_NXA; ++i ) {
        y[i] = x[i];
    }
    for( i = 0; i < ACADO_NU; ++i ) {
        y[ACADO_NX+ACADO_NXA+i] = u[i];
    }
    for( i = 0; i < ACADO_NP; ++i ) {
        y[ACADO_NX+ACADO_NXA+ACADO_NU+i] = p[i];
    }
    for( i = 0; i < ACADO_NDX; ++i ) {
        y[ACADO_NX+ACADO_NXA+ACADO_NU+ACADO_NP+i] = x[ACADO_NX+ACADO_NXA+i];
    }
    
    plhs[0] = mxCreateDoubleMatrix(ACADO_NX+ACADO_NXA+ACADO_NDX,1,mxREAL);
    f = mxGetPr(plhs[0]);
    
    acado_rhs( y,f );

    for( i = 0; i < ACADO_NDX; ++i ) {
        f[ACADO_NX+ACADO_NXA+i] = f[i];
    }
    for( i = 0; i < ACADO_NDX; ++i ) {
        f[i] = x[ACADO_NX+ACADO_NXA+i];
    }
}

